### ISSUE TITLE
Clarity around getPersisted returning undefined

### ISSUE THREAD

**Issue by wattroll** [tinyplex/tinybase#161]
### Describe the bug

Hi. Thank you for a great project. I am working on another persister and stumbled onto a small issue.

The type of `createCustomPersister`'s [`getPersisted` parameter](https://github.com/tinyplex/tinybase/blob/2f3e053c6d4aba24e6568787f0e2b4caa23c7ebd/src/persisters/index.ts#L81) permits returning `Promise<undefined>`, but during the `load()` the type of returned value is coerced ([in `setContentOrChanges`](https://github.com/tinyplex/tinybase/blob/2f3e053c6d4aba24e6568787f0e2b4caa23c7ebd/src/persisters/index.ts#L151)) skipping the check for `undefined` which results in e.g. `store.setContent` failing like this:

```
Got TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at setContent (...../tinybase/5.0.3/index.js:2934:22)
    at setContentOrChanges (...../tinybase/5.0.3/index.js:1223:28)
    .....
```

**Comment by wattroll** [comment]
### Expected behavior

I think that `persister.load()` shouldn't reject when `getPersisted` returns `undefined` since returning `undefined` is permitted by a type and seems to me like a reasonable result of `getPersisted` when there was no content to load.

The documentation says:

> getPersisted -- An asynchronous function which will fetch content from the persistence layer (or `undefined` if not present).

It's not entirely clear to me (based on documentation alone) whether the expected behavior upon returned `undefined` is that the store will be emptied akin to returning `[{},{}] ` or just left unchanged. I suppose it's handy if returning `undefined` means "the data is not available, don't change anything" otherwise the only way to do that is by rejecting the promise which might be not ideal in cases when it's completely normal that i.e. remote persister isn't able to pull the remote data most of the time and there is no need to be logging an "oh no we are ofline" error regularly.

**Comment by jamesgpearce** [comment]
Great analysis. I'm a bit surprised that undefined throws (the Store should ignore invalid content silently) but I'm sure you're right. Once I repro, I'll make sure that _is_ the case, since yes, undefined kind of implies either the underlying file/store/source doesn't exist and the initialContent can be taken. Seems I need to dive back into this corner of the project!

**Comment by jamesgpearce** [comment]
I can't get it to throw, per se... it appears as an ignored error:

```js
test.only('does not error on getPersister returning undefined', async () => {
  const store = createStore();
  store.setTables({t1: {r1: {c1: 1}}});
  const persister = createCustomPersister(
    store,
    async () => {
      console.log('undefined!!!');
      return undefined;
    },
    async () => {},
    () => 0,
    () => 0,
    console.warn,
  );
  await persister.load();
  expect(store.getTables()).toEqual({t1: {r1: {c1: 1}}});
});
```

Gives:
```
    console.warn
      TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
          at setContent (/Users/james/code/github/tinyplex/tinybase/dist/index.js:2934:22)
          at setContentOrChanges (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1223:27)
          at setContentOrChanges (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1232:11)
          at run (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1207:11)
          at schedule (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1304:5)
          at Object.load (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1230:7)
          at Object.<anonymous> (/Users/james/code/github/tinyplex/tinybase/test/unit/persisters/persisters.test.ts:351:3)
```

**Comment by jamesgpearce** [comment]
I can provoke similar behavior, however, by firing the persister listener with invalid content (because of the way the various parts of the persister are wrapped in try/catches):

```js
test.only('autoLoad silent if persister listener returns invalid', async () => {
  let triggerListener = () => {};
  const store = createStore();
  store.setTables({t1: {r1: {c1: 1}}});
  const persister = createCustomPersister(
    store,
    async () => 1 as any,
    async () => {},
    (listener) => (triggerListener = listener),
    () => 0,
  );
  await persister.startAutoLoad();
  triggerListener(1 as any);
  expect(store.getTables()).toEqual({t1: {r1: {c1: 1}}});
});
```

Gives:

```
TypeError: number 1 is not iterable (cannot read property Symbol(Symbol.iterator))
    at setContent (/Users/james/code/github/tinyplex/tinybase/dist/index.js:1720:22)
    at setContentOrChanges (/Users/james/code/github/tinyplex/tinybase/dist/index.js:756:215)
    at /Users/james/code/github/tinyplex/tinybase/dist/index.js:785:11
    at Object.<anonymous> (/Users/james/code/github/tinyplex/tinybase/test/unit/persisters/persisters.test.ts:723:3
```

So will land both of theses test cases as well as more tolerance on the setContent method.

**Comment by jamesgpearce** [comment]
Tests in https://github.com/tinyplex/tinybase/commit/fbafcf19df29af69d73e1cf2a9eac407fc962010 and changes to the way things are handled in https://github.com/tinyplex/tinybase/commit/9f4d9eb211959acfa0787600dc197bbd577598df - both released in v5.0.5. Let me know if that fits the bill. If not, feel free to re-open with more suggestions!

**Comment by wattroll** [comment]
> I can't get it to throw, per se... it appears as an ignored error:

You are totally right. I had a better look and confirmed that the actual throw of an error was coming from my own test harness (which throws the ignored errors when running my persister to expose potential issues in it).
Sorry about not reproducing it properly. Apparently I was too quick to draw a wrong conclusion upon seeing an unintentional-looking "TypeError: undefined is not iterable" coupled with type coercion at its source.

**Comment by wattroll** [comment]
> Tests in https://github.com/tinyplex/tinybase/commit/fbafcf19df29af69d73e1cf2a9eac407fc962010 and changes to the way things are handled in https://github.com/tinyplex/tinybase/commit/9f4d9eb211959acfa0787600dc197bbd577598df - both released in v5.0.5.

Looks great. Thanks! I believe on developer-end it's a lot nicer to see suggestive "Error: Content is not an array" in the log than a dreaded "TypeError: undefined is not iterable".

**Comment by wattroll** [comment]
I wanted to understand the new behavior properly to make sure my mental model is correct, if you have a moment for this, could you confirm that I got it right:

1. If `getContent` returns invalid Content that is not an Array (e.g. `undefined`, `null`, `{ error: "Uuuupsie" }`, `42`):
   - [`validateContent`](https://github.com/tinyplex/tinybase/blob/c53bfee160969d43ab5eeb546c52e13dc3208fc6/src/store/index.ts#L249) returns false
     - store is left unchanged or set to `initialContent` (if available),
     - `onIgnoredError` is invoked with error message `` `Content is not an array ${content}` ``.
2. If `getContent` returns invalid Content that is an Array (e.g. `[]`, `["hey", "there"]`, `[[],[]]`)
    - [`validateTables`](https://github.com/tinyplex/tinybase/blob/c53bfee160969d43ab5eeb546c52e13dc3208fc6/src/store/index.ts#L251) return false
       - store's tables are left unchanged
       - InvalidCellListener is invoked as `listener(store, undefined, undefined, undefined, [undefined])`
    - [`validateValues`](https://github.com/tinyplex/tinybase/blob/c53bfee160969d43ab5eeb546c52e13dc3208fc6/src/store/index.ts#L304) return false
       - store's values are left unchanged 
       - InvalidValueListener is invoked as `listener(store, undefined, [undefined])`

**Comment by wattroll** [comment]
I don't have a strong opinion on what's the best behavior for when `getContent` returns a value that wouldn't have passed a type-checker for `type Content = [Tables, Values]`. However `undefined` is explicitly permitted by `getContent`'s type signature and is documented to mean that content is not present. Because of that it doesn't seem right to me that it gets treated the same as other completely invalid values.

**Comment by wattroll** [comment]
Here is a concrete use-case when `getPersisted` wants to say "I've checked with remote source and our data is up-to-date, keep it as-it-is".

The current version of a remote persister keeps track of the last ETag and issues HEAD requests comparing old ETag with current (which is the best way to be compatible with every HTTP server that provides ETags). A variation of it could shoot the real request right-away with `If-None-Match` header containing the last ETag (which won't work well with servers that don't support that header, but otherwise will avoid the extra round-trip). Something like:

```typescript
const getPersisted = async (): Promise<Content | undefined> => {
  const headers = lastEtag === null ? [] : { 'if-none-match': lastEtag };
  const response = await fetch(loadUrl, { headers });
  if (response.status != 304) {
    lastEtag = getETag(response);
    return jsonParse(await response.text());
  }
};
```

In this case it's really undesired for `undefined` to be considered as some kind of error, because it indicates that everything is alright and we are in sync with the remote source. Still, using `undefined` as a sentinel for "leave the store unchanged" comes with it's own issues (especially in untyped javascript with returns inside condition branches), so I really don't want to be advocating for it's use. But it seems to me that it's useful for `getPersisted` to be able to communicate that somehow.

**Comment by jamesgpearce** [comment]
Yeah, that's a good point. Still some refinement to be done here (at least with making the semantics of undefined clearer). Your mental model on the whole is correct (except in 1, the validateContent is never reached... the persister checks it's an array for itself to decide whether to throw/log or not - since the Store is always silent by design)

**Comment by wattroll** [comment]
You are right, it seems that this is mostly about clarifying the meaning of `undefined`. When opening this issue I haven't yet realized how for example `initialContent` parameter ties into this. Now looking around the code and reading the rest of documentation it seems that my earlier intuition was wrong and `undefined` was never intended to be a sentinel value to mean "content is *currently* not available" or "content hasn't changed since last load".

So returning `undefined` is appropriate when persister is pointed at the resource that is *known* to contain no content. The purpose of returning `undefined` instead of throwing an error could be to indicate that `initialContent` can *safely* be used to initialize that resource (without a risk of overwriting the existing, but temporarily not available content). I suppose it also could be expected that a lawful persister pointed at a well-functioning resource will not return `undefined` after a successful `setPersisted`.

Is this correct more or less? I tried to think of some examples where `getPersisted()` could reasonably return `undefined` instead of throwing or returning empty content:

- resource is `localStorage` and specified `storageName` key doesn't exist, `setPersisted` will set the key;
- resource is HTTP endpoint and the GET returns 404, after `setPersisted` does a POST it can be expected that `GET` will return some content;
- resource is json-persisted sqlite database and `tinybase_content` table does not exist and/or is empty, `setPersisted` will ensure  the table exists and a insert a row with json content;
- resource is tabular-persisted sqlite database and none of tables specified in the `load` exist, `setPersisted` will ensure that all tables specified in `save` exist.

**Comment by jamesgpearce** [comment]
Fixed in the current beta branch and release coming soon!
