### ISSUE TITLE
YjsPersister errors in case startAutoLoad is run before startAutoSave

### ISSUE THREAD

**Issue by nikgraf** [tinyplex/tinybase#186]
### Describe the bug

This is the error I see:

```
Error: Content is not an array undefined
    at errorNew (/node_modules/tinybase/persisters/persister-yjs/index.js:36:9)
    at _callee2$ (/node_modules/tinybase/persisters/persister-yjs/index.js:447:27)
    at tryCatch (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.eval (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.eval [as next] (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
    at _next (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
```

The issue is if I run `startAutoSave` before `startAutoLoad` it wipes the Yjs object.

### Your Example Website or App

https://codesandbox.io/p/sandbox/x77hnc

### Steps to Reproduce the Bug or Issue

Run this code:

```ts
const doc1 = new Doc();
const store1 = createStore();
const persister1 = createYjsPersister(store1, doc1, "space", (error) => {
  console.log("YjsPersister Error:", error);
});
await persister1.startAutoLoad();
await persister1.startAutoSave();
```

### Expected behavior

Graceful handling of the error

### Platform

- Tinybase 5.3

**Comment by nikgraf** [comment]
Yeah in our case there is no need for initial content since the sync engine will provide the initial content. Is this a use-case that's not desired or should I provide just dummy initial content?

**Comment by jamesgpearce** [comment]
I see - makes sense! Ok so let me do this: if you provide any initial content (even [{},{}]) the error will be suppressed. Will that work?

**Comment by nikgraf** [comment]
sounds good to me 👍

**Comment by jamesgpearce** [comment]
Fix in https://github.com/tinyplex/tinybase/commit/5de84aa16f43f4504f05054b013fd6877e17afa0 - should appear in the next release!
